### ISSUE TITLE
Add validation

### ISSUE THREAD

**Issue by ashkema** [imbieras/shopipy#13]
- Create **phone number** validation for the following endpoints: 
/Users [post] 
 /Users [put]
 currently system accepts "123456" as a phone number.
- In `JsonStringEnumConverter` set **allowIntegerValues** to **false** 
Currently, the system accepts numeric values for enums, and if an undefined enum value is passed as a number, it is still saved.

**Comment by Domarkaite** [comment]
the first one is redundant. the second one i added in the newest pr
